version: '3'

services:
  nginx:
    container_name: "nginx"
    image: nginx:1.13.10-alpine
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./.docker/nginx/html:/var/www/html
      - ./src:/var/www/html
 
  php:
    container_name: "php"
    build: ./.docker/php
    env_file: .env
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    volumes:
      # - ./.docker/nginx/html:/var/www/html
      - ./src:/var/www/html

  mysql:
    container_name: "mysql"
    image: mysql:5.7.21
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./.docker/mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql

volumes:
  db-data: